### PR TITLE
Add new Google Play files for Firefox 57 and 58 beta

### PR DESCRIPTION
**Pull request by Delphine**

### CODE REVIEW

**Comment by flodolo** [comment]
Note the amount of content added since I've updated the shipping locales
https://github.com/mozilla-l10n/appstores/pull/104/commits/93e08d4568169f6f98e54b8b9959bf235f2c3a0c

**Review by flodolo — APPROVED** [review]
Updated string order and Bengali string, add content for new locales.

**Comment by TonnesM** [comment]
Small thing: "Added the ability for users to add websites to home screen like native applications".

I would rather refer to "web pages", as per definition, a website is a huge collection of web pages, and users can add several pages for the same website. Mozilla-wide, the difference isn’t entirely clear or this is not taken into account consistently (for products as well as web pages), but there is a difference I’d like to "stand up" for. ;)

**Comment by flodolo** [comment]
Technically, you're absolutely right. Practically, I think users don't distinguish between them: you'll hear them talk about websites, never web pages.

Having said that, in this context, I think website is correct: PWA, unlike shortcuts, are not just for one specific page.
https://hacks.mozilla.org/2017/10/progressive-web-apps-firefox-android/

**Pull request merged**
