### PR TITLE
[id-ID] Translated id/description_beta_page.lang

### PR DESCRIPTION
**Pull request by luthfianto**

### CODE REVIEW

**Comment by flodolo** [comment]
@rodin Can you review this PR and merge it?

**Comment by rodin** [comment]
@rilut thanks! Few corrections:
- customization: ubahsuaian
- https://www.mozilla.org/en-US/firefox/mobile/platforms/: https://www.mozilla.org/id/firefox/mobile/platforms/

@flodolo: r=me with those fixed

**Comment by luthfianto** [comment]
@rodin thanks, fixed.

**Comment by flodolo** [comment]
Manually squashed and merged in https://github.com/mozilla-l10n/appstores/commit/d2a4ea5e065e5f0d306346aaa023fedeaa3a16bd

Not sure why GitHub didn't pick it up automatically.

Thanks both :+1:

**Pull request closed without merging**
